### ISSUE TITLE
Data seems to be getting corrupted after container removal

### ISSUE THREAD

**Issue by dmelo** [PeterGrace/opentsdb-docker#29]
OpenTSDB stops working after a `docker-compose down & docker-compose up`. Only starts working again after I delete all volumes, after it can recreate clean ones. I think that perhaps some data is getting corrupted after the shutdown. Is there a way to check/fix this kind of problem on container start? It is not a good thing to have to wipe all the data after the container is removed.

```
opentsdb                  | 2018-06-20 17:37:19,208 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:47044
opentsdb                  | 2018-06-20 17:37:19,209 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.ZooKeeperServer: Client attempting to establish new session at /127.0.0.1:47044
opentsdb                  | 2018-06-20 17:37:19,213 INFO  [SyncThread:0] server.ZooKeeperServer: Established session 0x1641e4572a60019 with negotiated timeout 5000 for client /127.0.0.1:47044
opentsdb                  | 2018-06-20 17:37:19,222 INFO  [ProcessThread(sid:0 cport:2181):] server.PrepRequestProcessor: Processed session termination for sessionid: 0x1641e4572a60019
opentsdb                  | 2018-06-20 17:37:19,224 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:47044 which had sessionid 0x1641e4572a60019
opentsdb                  | 2018-06-20 17:37:19,227 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:47048
opentsdb                  | 2018-06-20 17:37:19,227 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.ZooKeeperServer: Client attempting to establish new session at /127.0.0.1:47048
opentsdb                  | 2018-06-20 17:37:19,230 INFO  [SyncThread:0] server.ZooKeeperServer: Established session 0x1641e4572a6001a with negotiated timeout 5000 for client /127.0.0.1:47048
opentsdb                  | 2018-06-20 17:37:19,245 INFO  [ProcessThread(sid:0 cport:2181):] server.PrepRequestProcessor: Processed session termination for sessionid: 0x1641e4572a6001a
opentsdb                  | 2018-06-20 17:37:19,250 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:47048 which had sessionid 0x1641e4572a6001a
opentsdb                  | 2018-06-20 17:37:19,254 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:47052
opentsdb                  | 2018-06-20 17:37:19,256 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.ZooKeeperServer: Client attempting to establish new session at /127.0.0.1:47052
opentsdb                  | 2018-06-20 17:37:19,274 INFO  [SyncThread:0] server.ZooKeeperServer: Established session 0x1641e4572a6001b with negotiated timeout 5000 for client /127.0.0.1:47052
opentsdb                  | 2018-06-20 17:37:19,296 INFO  [ProcessThread(sid:0 cport:2181):] server.PrepRequestProcessor: Processed session termination for sessionid: 0x1641e4572a6001b
opentsdb                  | 2018-06-20 17:37:19,301 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:47052 which had sessionid 0x1641e4572a6001b
opentsdb                  | 2018-06-20 17:37:19,305 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:47056
opentsdb                  | 2018-06-20 17:37:19,306 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.ZooKeeperServer: Client attempting to establish new session at /127.0.0.1:47056
opentsdb                  | 2018-06-20 17:37:19,307 INFO  [SyncThread:0] server.ZooKeeperServer: Established session 0x1641e4572a6001c with negotiated timeout 5000 for client /127.0.0.1:47056
opentsdb                  | 2018-06-20 17:37:19,328 INFO  [ProcessThread(sid:0 cport:2181):] server.PrepRequestProcessor: Processed session termination for sessionid: 0x1641e4572a6001c
opentsdb                  | 2018-06-20 17:37:19,329 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:47056 which had sessionid 0x1641e4572a6001c
opentsdb                  | Exception in thread "main" java.lang.RuntimeException: Initialization failed
opentsdb                  | 	at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
opentsdb                  | Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
opentsdb                  | 	at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169)
opentsdb                  | 	at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:142)
opentsdb                  | 	at com.stumbleupon.async.DeferredGroup.access$000(DeferredGroup.java:36)
opentsdb                  | 	at com.stumbleupon.async.DeferredGroup$1Notify.call(DeferredGroup.java:82)
opentsdb                  | 	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
opentsdb                  | 	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
opentsdb                  | 	at com.stumbleupon.async.Deferred.access$300(Deferred.java:430)
opentsdb                  | 	at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366)
opentsdb                  | 	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
opentsdb                  | 	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
opentsdb                  | 	at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313)
opentsdb                  | 	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284)
opentsdb                  | 	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
opentsdb                  | 	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
opentsdb                  | 	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720)
opentsdb                  | 	at org.hbase.async.HBaseClient.tooManyAttempts(HBaseClient.java:2558)
opentsdb                  | 	at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:2420)
opentsdb                  | 	at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:2444)
opentsdb                  | 	at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:2427)
opentsdb                  | 	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
opentsdb                  | 	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
opentsdb                  | 	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
opentsdb                  | 	at org.hbase.async.HBaseClient$ZKClient$ZKCallback.processResult(HBaseClient.java:4394)
opentsdb                  | 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561)
opentsdb                  | 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
opentsdb                  | Caused by: org.hbase.async.NonRecoverableException: Too many attempts: HBaseRpc(method=getClosestRowBefore, table="hbase:meta", key=[116, 115, 100, 98, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 65, 115, 121, 110, 99, 72, 66, 97, 115, 101, 126, 112, 114, 111, 98, 101, 126, 60, 59, 95, 60, 44, 58], region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key=""), attempt=11, timeout=-1, hasTimedout=false)
opentsdb                  | 	at org.hbase.async.HBaseClient.tooManyAttempts(HBaseClient.java:2556)
opentsdb                  | 	... 9 more
```

```
$ docker --version
Docker version 18.05.0-ce, build f150324
$ docker-compose --version
docker-compose version 1.21.2, build a133471
```

And here is the docker-compose.yml that concerns the OpenTSDB:

```
    container_name: opentsdb
    image: petergrace/opentsdb-docker:latest
    restart: always
    networks:
      - dbnet
    ports:
      - 4242:4242
      - 60030:60030
    volumes:
      - type: ${OPENTSDB_FSTYPE:-volume}
        source: "${OPENTSDB_FSSOURCE}"
        target: /data/hbase
      - tsdb_tmp:/tmp
```

I'm using a bind volume.

**Comment by dmelo** [comment]
Just now I realised the big warning on the README saying I should give opentsdb at least 30 seconds to shutdown. I'm sorry about the noise.

**Comment by PeterGrace** [comment]
Thanks a bunch for your help, I've merged this PR.
