### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cindoum** [PeterGrace/opentsdb-docker#33]
Hi,

I am using the latest version of the docker image (docker version 1809). 

It seem that the java heap get full and crash opentsdb (or hbase). This occur every night after been running for a few hours. I have about 25 scollector (https://bosun.org/scollector/) running and sending data to bosun, which send it to opentsdb.

It is running on a Linux (debian) virtual machine with 16GO of memory.

Here is the stack 
```
2019-01-09 03:17:31,572 FATAL [main-EventThread] regionserver.HRegionServer: ABORTING region server otsdb-host,46227,1546900378726: regionserver:46227-0x1682a7288c00001, quorum=localhost:2181, baseZNode=/hbase regionserver:46227-0x1682a7288c00001 received expired from ZooKeeper, aborting
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.connectionEvent(ZooKeeperWatcher.java:692)
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.process(ZooKeeperWatcher.java:624)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
2019-01-09 03:17:31,572 FATAL [main-EventThread] regionserver.HRegionServer: RegionServer abort: loaded coprocessors are: [org.apache.hadoop.hbase.coprocessor.MultiRowMutationEndpoint]
2019-01-09 03:17:31,572 INFO  [RS:0;otsdb-host:46227] regionserver.SplitLogWorker: Sending interrupt to stop the worker thread
2019-01-09 03:17:31,573 INFO  [RS:0;otsdb-host:46227] regionserver.HRegionServer: Stopping infoServer
Exception in thread "pool-2-thread-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-1"
Exception in thread "pool-1-thread-8" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-12" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-10" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space.
```
It seem that i still have a enough free memory 
``` 
someone@is-dev-tool-lx:/docker# free -m
                   total        used        free      shared  buff/cache   available
Mem:          16051        8423        7215          16         411        7348
Swap:         16380        1529       14851
```
I can provide more information if required. I do not know java at all (neither hbase) so i dont really know what information to provide...

Thank you

**Comment by cindoum** [comment]
This morning again when i get to the office, openTsdb is unreachable. Everything was working fine yesterday...

From what i can see, it seem that 23:02 yesterday to 3:44 this morning there was nothing recorded into opentsdb. Then it start recording rows but was not accessible when called from the api (from bosun). 
![image](https://user-images.githubusercontent.com/2387496/50975781-60af0200-14bc-11e9-9457-a4a3fe84f8a3.png)

Here is the full log (what i can retrieve) :
[debug.txt](https://github.com/PeterGrace/opentsdb-docker/files/2745810/debug.txt)

**Comment by cindoum** [comment]
For now ive made a cron to restart opentsdb every day and it seem to work but would appreciate some help ;)

**Comment by PeterGrace** [comment]
I believe this is related to the fact that JDK7 doesn't understand how to properly calculate heap sizes inside of a container.  I've got a local branch where I'm testing against jdk11, and will hopefully merge that in which should resolve this issue.

**Comment by PeterGrace** [comment]
...and unfortunately jdk11 deprecated some libraries that opentsdb uses.  Great.  The options for cgroup memory management in java are apparently in jdk8 if you enable `-XX:+UnlockExperimentalVMOptions` and `-XX:+UseCGroupMemoryLimitForHeap`, which I'll see about doing next.

**Comment by PeterGrace** [comment]
@cindoum and @wolfman2g1, can you two retest with the latest image?  It now uses JDK 8 and will calculate heap based on what the cgroup is reporting as viable memory available, which might help this issue.  It's currently enqueued to build at Docker Hub so it should be available in the registry within the hour.

**Comment by dancohen21** [comment]
@PeterGrace I'm running into this issue.... any ideas?
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError="kill -9 %p"
#   Executing /bin/sh -c "kill -9 11"...
/opt/bin/start_hbase.sh: line 6:    11 Killed                  /opt/hbase/bin/hbase master start

**Comment by dancohen21** [comment]
> For now ive made a cron to restart opentsdb every day and it seem to work but would appreciate some help ;)

@cindoum - how were you able to do this?
Thanks, Dan

**Comment by PeterGrace** [comment]
@dancohen21 not sure if you're still running into issues here, but I'm guessing @cindoum wrote a script that does a `docker stop <container_name> && docker start <container_name>` or something similar.  With regards to out of memory errors, those can be highly situationally dependent on the hardware you're running.

I'm going to close this as it is dated and haven't seen many other people reporting the issue, but if the problems persist please feel free to re-open.
