### ISSUE TITLE
Container fails when host go to sleep mode

### ISSUE THREAD

**Issue by AlexisBRENON** [PeterGrace/opentsdb-docker#38]
Hi,

Thanks for the very easy to use image.
Before deploying my setup, I do some tests on my laptop.
Each time I put it in sleep mode, after resuming, I cannot send any values to the OpenTSDB database.

Here is the error:

```
opentsdb_1  | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/otsdb-host,37183,1590089865286
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
opentsdb_1  |   at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1532)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getChildren(RecoverableZooKeeper.java:292)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchForNewChildren(ZKUtil.java:462)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchThem(ZKUtil.java:490)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenBFSAndWatchThem(ZKUtil.java:1490)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursivelyMultiOrSequential(ZKUtil.java:1412)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursively(ZKUtil.java:1294)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.ReplicationQueuesZKImpl.removeAllQueues(ReplicationQueuesZKImpl.java:195)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.ReplicationSourceManager.join(ReplicationSourceManager.java:322)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.Replication.join(Replication.java:206)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.Replication.stopReplicationService(Replication.java:198)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.stopServiceThreads(HRegionServer.java:2278)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1144)
opentsdb_1  |   at java.lang.Thread.run(Thread.java:748)
opentsdb_1  | 2020-05-22 06:55:05,395 ERROR [RS:0;otsdb-host:37183] zookeeper.ZooKeeperWatcher: regionserver:37183-0x17238bdd2400001, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
opentsdb_1  | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/otsdb-host,37183,1590089865286
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
opentsdb_1  |   at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1532)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getChildren(RecoverableZooKeeper.java:292)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchForNewChildren(ZKUtil.java:462)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchThem(ZKUtil.java:490)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenBFSAndWatchThem(ZKUtil.java:1490)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursivelyMultiOrSequential(ZKUtil.java:1412)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursively(ZKUtil.java:1294)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.ReplicationQueuesZKImpl.removeAllQueues(ReplicationQueuesZKImpl.java:195)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.ReplicationSourceManager.join(ReplicationSourceManager.java:322)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.Replication.join(Replication.java:206)
opentsdb_1  |   at org.apache.hadoop.hbase.replication.regionserver.Replication.stopReplicationService(Replication.java:198)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.stopServiceThreads(HRegionServer.java:2278)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1144)
opentsdb_1  |   at java.lang.Thread.run(Thread.java:748)
opentsdb_1  | 2020-05-22 06:55:05,395 INFO  [RS:0;otsdb-host:37183] ipc.RpcServer: Stopping server on 37183
opentsdb_1  | 2020-05-22 06:55:05,396 INFO  [RpcServer.listener,port=37183] ipc.RpcServer: RpcServer.listener,port=37183: stopping
opentsdb_1  | 2020-05-22 06:55:05,397 INFO  [RpcServer.responder] ipc.RpcServer: RpcServer.responder: stopped
opentsdb_1  | 2020-05-22 06:55:05,397 INFO  [RpcServer.responder] ipc.RpcServer: RpcServer.responder: stopping
opentsdb_1  | 2020-05-22 06:55:05,401 WARN  [RS:0;otsdb-host:37183] regionserver.HRegionServer: Failed deleting my ephemeral node
opentsdb_1  | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/otsdb-host,37183,1590089865286
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
opentsdb_1  |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
opentsdb_1  |   at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.delete(RecoverableZooKeeper.java:178)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1250)
opentsdb_1  |   at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1239)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.deleteMyEphemeralNode(HRegionServer.java:1502)
opentsdb_1  |   at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1152)
opentsdb_1  |   at java.lang.Thread.run(Thread.java:748)
opentsdb_1  | 2020-05-22 06:55:05,402 INFO  [RS:0;otsdb-host:37183] regionserver.HRegionServer: stopping server otsdb-host,37183,1590089865286; zookeeper connection closed.
opentsdb_1  | 2020-05-22 06:55:05,402 INFO  [RS:0;otsdb-host:37183] regionserver.HRegionServer: RS:0;otsdb-host:37183 exiting
opentsdb_1  | 2020-05-22 06:55:05,413 INFO  [Shutdown] mortbay.log: Shutdown hook executing
opentsdb_1  | 2020-05-22 06:55:05,413 INFO  [Shutdown] mortbay.log: Shutdown hook complete
opentsdb_1  | 2020-05-22 06:55:05,415 INFO  [Thread-6] regionserver.ShutdownHook: Shutdown hook starting; hbase.shutdown.hook=true; fsShutdownHook=org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer@5505ae1a
opentsdb_1  | 2020-05-22 06:55:05,418 INFO  [Thread-6] regionserver.ShutdownHook: Starting fs shutdown hook thread.
opentsdb_1  | 2020-05-22 06:55:05,420 INFO  [Thread-6] regionserver.ShutdownHook: Shutdown hook finished.
opentsdb_1  | stopping hbase
^CGracefully stopping... (press Ctrl+C again to force)
```

As you can see, I'm using docker-compose. Maybe setting a `restart` policy can fix my problem, but perhaps you can handle this at the image side.

Kind.
Alexis

**Comment by PeterGrace** [comment]
Hi @AlexisBRENON,  I'm not certain there is an easy way to work around this issue -- from the errors it looks like the zookeeper token expires because of the time shift.  Changing that would require changes to zookeeper, I think, but I'm not 100% certain.  You might want to take the issue up with the ZooKeeper group.  If they have a fix that we could easily integrate I would consider putting it in.
